# Generated by Django 3.0.8 on 2020-09-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200902_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='users/static/users/images/profile_default.gif', null=True, upload_to='images/'),
        ),
    ]
