# Generated by Django 3.0.8 on 2020-09-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200903_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='she_codes_news/users/static/users/images/profile_default.gif', null=True, upload_to='images/'),
        ),
    ]
