# Generated by Django 3.0.8 on 2020-08-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200825_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='img_url',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='story_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
