# Generated by Django 3.0.8 on 2020-09-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200901_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(default='All cafes', max_length=200),
        ),
    ]
